{% set name = "unixODBC" %}
{% set version = "2.3.6" %}
{% set sha256 = "88b637f647c052ecc3861a3baa275c3b503b193b6a49ff8c28b2568656d14d69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.unixodbc.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  skip: true  # [win]
  run_exports:
    # excellent within minor versions: https://abi-laboratory.pro/tracker/timeline/unixodbc/
    - {{ pin_subpackage('unixodbc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f $PREFIX/lib/libodbc.2.dylib  # [osx]
    - test -f $PREFIX/lib/libodbc.dylib  # [osx]
    - test -f $PREFIX/lib/libodbcinst.2.dylib  # [osx]
    - test -f $PREFIX/lib/libodbcinst.dylib  # [osx]
    - test -f $PREFIX/lib/libodbc.so.2.0.0  # [linux]
    - test -f $PREFIX/lib/libodbc.so  # [linux]
    - test -f $PREFIX/lib/libodbcinst.so.2.0.0  # [linux]
    - test -f $PREFIX/lib/libodbcinst.so  # [linux]

about:
  home: http://www.unixodbc.org/
  license: LGPL-2.1
  license_file: COPYING
  license_family: LGPL
  summary: 'ODBC on non MS Windows platforms'
  description: |
    The unixODBC Project goals are to develop and promote unixODBC to be the
    definitive standard for ODBC on non MS Windows platforms. This is to
    include GUI support for both KDE and GNOME.
  doc_url: http://www.unixodbc.org/doc/UserManual/

extra:
  recipe-maintainers:
    - MathMagique
    - xhochy
    - msarahan
