travis:
  secure:
    BINSTAR_TOKEN: EZBYOhF6XUUoAskXNwoMbVX6HK5KafzFa/w1TmnR02OL+qB2cNlGohi+BnQy/9jwDfJ1htb4HO9o4Y3UdZZ6Jukh40Thaf/NX1yqfpTF/PnWEQd2nkoHLwc11ajtfPeZu1dLgn9q5NZ/EjJdJSm9Y+h77CjOd6jxy5tHxegbVPF/D1ykFNqoA+ufe4tXERlVHw1/HWfL40F8oaAVddXnzakVIGB+R87jR3JX/qxetQt8AxJC53TNDUURgfgMhndy/v3NIf6cTY85iHdwWKqUoFdou5P7debJmP7MecSHLJIXKffsiH2uoRPQMsT4sLzswGbTqKUG+aBwdiMS7yyveeESaxnLH7t0DSdsPlpFCYfQesFXnJTQgHTbZ1gxwSYlu/TlxsoblrYZO7GSjnqjlo+Tt8k1GVf/P5DG/kEZat1Mihs3wYTY6XSGzYGsR94+JpluLSWILWBgDN/vvnDI/k9r0giM9VxI8iBs+wEeDthNjAD0kUUROPGWV62Xa6Xk89PNI+YLmkSK7uzlZHOZO8GQU1o83BIRT1O9UhxLlCHFJF23SX8U9sG3xCLlW6X0bcolW3pkHhW2f+fGZ7taI6OvqfrCUhmszbaH3/b4Nek3c7zouH1C5KEnj/Ac08tM9cnoxQCCQEER8Vp1IE++bYXlYsb/EQtYmctPMo/4CqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
